using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using WebApplication1.Models;
using WebApplication1.Services;

namespace WebApplication1.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(
            UserManager<ApplicationUser> userManager,
            IEmailSender emailSender)
        {
            _userManager  = userManager;
            _emailSender  = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; } = new InputModel();

        public class InputModel
        {
            [Required(ErrorMessage = "O email é obrigatório.")]
            [EmailAddress(ErrorMessage = "Endereço de email inválido.")]
            public string Email { get; set; } = string.Empty;
        }

        // GET /Identity/Account/ForgotPassword
        public void OnGet() { }

        // POST /Identity/Account/ForgotPassword
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // ── 1. Look up the user by email ──────────────────────────────────
            var user = await _userManager.FindByEmailAsync(Input.Email);

            // Security best practice: always redirect to the confirmation page,
            // even when the user is not found. This prevents email enumeration
            // attacks (an attacker cannot tell whether an account exists).
            if (user == null)
            {
                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            // ── 2. Generate a secure, time-limited password reset token ───────
            // The token is generated by ASP.NET Core Identity's token provider
            // (DataProtectorTokenProvider by default). It is cryptographically
            // signed and expires after the configured lifetime (default: 1 day).
            var token = await _userManager.GeneratePasswordResetTokenAsync(user);

            // ── 3. URL-encode the token for safe transport in a query string ──
            // Tokens contain characters (+, =, /) that are not URL-safe.
            // WebEncoders.Base64UrlEncode converts to a URL-safe Base64 string.
            var encodedToken = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(token));

            // ── 4. Build the absolute reset URL ───────────────────────────────
            // Url.Page generates a relative URL; the second overload with
            // protocol/host produces an absolute URL required for email links.
            var callbackUrl = Url.Page(
                pageName        : "/Account/ResetPassword",
                pageHandler     : null,
                values          : new { area = "Identity", token = encodedToken, email = Input.Email },
                protocol        : Request.Scheme   // "https" in production
            );

            // ── 5. Compose and send the branded HTML email ────────────────────
            var htmlBody = $@"
                <div style=""font-family: 'Segoe UI', Arial, sans-serif; max-width: 560px; margin: 0 auto; background-color: #f8f9fa; padding: 32px;"">
                    <div style=""background: white; border-radius: 12px; padding: 40px; box-shadow: 0 4px 12px rgba(0,0,0,0.08);"">

                        <div style=""text-align: center; margin-bottom: 28px;"">
                            <span style=""font-size: 1.8rem; font-weight: 700; color: #212529;"">✂ BarberLoc</span>
                        </div>

                        <h2 style=""font-size: 1.4rem; font-weight: 600; color: #212529; margin-bottom: 8px;"">
                            Redefinir a sua senha
                        </h2>
                        <p style=""color: #6c757d; line-height: 1.6; margin-bottom: 24px;"">
                            Recebemos um pedido para redefinir a senha da conta associada a este email.
                            Clique no botão abaixo para criar uma nova senha.
                        </p>

                        <div style=""text-align: center; margin-bottom: 28px;"">
                            <a href=""{HtmlEncoder.Default.Encode(callbackUrl!)}""
                               style=""display: inline-block; background-color: #0d6efd; color: #ffffff;
                                      padding: 14px 32px; border-radius: 8px; text-decoration: none;
                                      font-weight: 600; font-size: 1rem;"">
                                Redefinir senha
                            </a>
                        </div>

                        <p style=""color: #6c757d; font-size: 0.85rem; line-height: 1.6;"">
                            Este link é válido por <strong>24 horas</strong>.
                            Se não solicitou a redefinição de senha, ignore este email — a sua conta está segura.
                        </p>

                        <hr style=""border: none; border-top: 1px solid #dee2e6; margin: 24px 0;"">

                        <p style=""color: #adb5bd; font-size: 0.8rem; text-align: center;"">
                            &copy; {DateTime.UtcNow.Year} BarberLoc. Todos os direitos reservados.
                        </p>
                    </div>
                </div>";

            await _emailSender.SendEmailAsync(
                toEmail : Input.Email,
                subject : "BarberLoc — Redefinição de senha",
                htmlBody: htmlBody
            );

            // ── 6. Redirect to the confirmation page ──────────────────────────
            return RedirectToPage("./ForgotPasswordConfirmation");
        }
    }
}
